### ISSUE TITLE
Issue with Astropy with stations that don't have an internet connection

### ISSUE THREAD

**Issue by dostuffthatmatters** [tum-esm/pyra#154]
Happening on stations, that don't have internet.

```python
2023-02-15 00:00:07.681125 UTC+0 - main - EXCEPTION - ValueError occured: Traceback (most recent call last):

  File "C:\Users\CEA P-Saclay\Documents\pyra\pyra-4.0.6\packages\core\main.py", line 116, in run
    m.run(config)

  File "C:\Users\CEA P-Saclay\Documents\pyra\pyra-4.0.6\packages\core\modules\opus_measurement.py", line 78, in run
    self.automated_process_handling()

  File "C:\Users\CEA P-Saclay\Documents\pyra\pyra-4.0.6\packages\core\modules\opus_measurement.py", line 276, in automated_process_handling
    if not self.low_sun_angle_present():

  File "C:\Users\CEA P-Saclay\Documents\pyra\pyra-4.0.6\packages\core\modules\opus_measurement.py", line 265, in low_sun_angle_present
    sun_angle_is_low: bool = utils.Astronomy.get_current_sun_elevation().is_within_bounds(

  File "C:\Users\CEA P-Saclay\Documents\pyra\pyra-4.0.6\packages\core\utils\astronomy.py", line 23, in get_current_sun_elevation
    sun_angle_deg = sun.transform_to(altaz).alt

  File "C:\Users\CEA P-Saclay\AppData\Local\Programs\Python\Python310\lib\site-packages\astropy\coordinates\sky_coordinate.py", line 675, in transform_to
    new_coord = trans(self.frame, generic_frame)

  File "C:\Users\CEA P-Saclay\AppData\Local\Programs\Python\Python310\lib\site-packages\astropy\coordinates\transformations.py", line 1479, in __call__
    curr_coord = t(curr_coord, curr_toframe)

  File "C:\Users\CEA P-Saclay\AppData\Local\Programs\Python\Python310\lib\site-packages\astropy\coordinates\transformations.py", line 1079, in __call__
    return supcall(fromcoord, toframe)

  File "C:\Users\CEA P-Saclay\AppData\Local\Programs\Python\Python310\lib\site-packages\astropy\coordinates\builtin_frames\icrs_observed_transforms.py", line 30, in icrs_to_observed
    astrom = erfa_astrom.get().apco(observed_frame)

  File "C:\Users\CEA P-Saclay\AppData\Local\Programs\Python\Python310\lib\site-packages\astropy\coordinates\erfa_astrom.py", line 53, in apco
    era = erfa.era00(*get_jd12(obstime, 'ut1'))

  File "C:\Users\CEA P-Saclay\AppData\Local\Programs\Python\Python310\lib\site-packages\astropy\coordinates\builtin_frames\utils.py", line 118, in get_jd12
    newtime = getattr(time, scale)

  File "C:\Users\CEA P-Saclay\AppData\Local\Programs\Python\Python310\lib\site-packages\astropy\time\core.py", line 1336, in __getattr__
    tm._set_scale(attr)

  File "C:\Users\CEA P-Saclay\AppData\Local\Programs\Python\Python310\lib\site-packages\astropy\time\core.py", line 584, in _set_scale
    args.append(get_dt(jd1, jd2))

  File "C:\Users\CEA P-Saclay\AppData\Local\Programs\Python\Python310\lib\site-packages\astropy\time\core.py", line 2051, in _get_delta_ut1_utc
    delta = iers_table.ut1_utc(jd1, jd2)

  File "C:\Users\CEA P-Saclay\AppData\Local\Programs\Python\Python310\lib\site-packages\astropy\utils\iers\iers.py", line 281, in ut1_utc
    return self._interpolate(jd1, jd2, ['UT1_UTC'],

  File "C:\Users\CEA P-Saclay\AppData\Local\Programs\Python\Python310\lib\site-packages\astropy\utils\iers\iers.py", line 414, in _interpolate
    self._check_interpolate_indices(i1, i, np.max(mjd))

  File "C:\Users\CEA P-Saclay\AppData\Local\Programs\Python\Python310\lib\site-packages\astropy\utils\iers\iers.py", line 712, in _check_interpolate_indices
    raise ValueError(INTERPOLATE_ERROR.format(auto_max_age))

ValueError: interpolating from IERS_Auto using predictive values that are more
than 30.0 days old.

Normally you should not see this error because this class
automatically downloads the latest IERS-A table.  Perhaps you are
offline?  If you understand what you are doing then this error can be
suppressed by setting the auto_max_age configuration variable to
``None``:

  from astropy.utils.iers import conf
  conf.auto_max_age = None
```

**Comment by dostuffthatmatters** [comment]
Here is the relevant section in the Astropy documentation: https://docs.astropy.org/en/stable/utils/iers.html#working-offline

**Comment by dostuffthatmatters** [comment]
We could also switch to https://github.com/arthur-e/suntransit since we don't need a high precision. https://arthur-e.github.io/suntransit/#__init__.sunrise_sunset does exactly what we want it to do: Get the time for a specific location and SZA.

**Comment by dostuffthatmatters** [comment]
I finally have an update on this:

We should use the `skyfield` library (https://github.com/skyfielders/python-skyfield/) and pick a suitable astronomical dataset from this list: https://ssd.jpl.nasa.gov/planets/eph_export.html

The later datasets (DE440, etc.) are probably bigger since they cover more years, so we should pick an earlier one that covers enough years into the future without being too big and include that in the repository (hence, the release).
