### ISSUE TITLE
`config.json` is deleted from somewhere

### ISSUE THREAD

**Issue by dostuffthatmatters** [tum-esm/pyra#207]
We noticed this twice on one of our systems at times where the system was running in automation. Pyra codebase doesn't include a call to delete the `config.json` file.

Here are the logs of the last time this happened:

```log
...
2023-11-27 08:33:59.554409 UTC+0 - main - INFO - Starting iteration
2023-11-27 08:33:59.564342 UTC+0 - upload - DEBUG - datalogger - releasing lock on local machine at "C:\MESSUNGEN\datalogger-copy-for-upload-test\dat\.do-not-touch"
2023-11-27 08:33:59.578248 UTC+0 - helios-thread - DEBUG - Thread is alive
2023-11-27 08:33:59.584210 UTC+0 - upload-thread - DEBUG - Thread is alive
2023-11-27 08:33:59.589177 UTC+0 - measurement-conditions - DEBUG - Coordinates used from CamTracker (lat, lon, alt): (48.15, 11.57, 540.0).
2023-11-27 08:33:59.610035 UTC+0 - measurement-conditions - DEBUG - Theoretical sun elevation is: 13.312 degrees.
2023-11-27 08:33:59.614011 UTC+0 - measurement-conditions - INFO - Running MeasurementConditions
2023-11-27 08:33:59.616989 UTC+0 - measurement-conditions - DEBUG - Decision mode for measurements is: automatic.
2023-11-27 08:33:59.619972 UTC+0 - measurement-conditions - INFO - Sun elevation as a trigger is considered.
2023-11-27 08:33:59.579243 UTC+0 - upload - DEBUG - datalogger - 2023-08-18: done (successful)
2023-11-27 08:33:59.642816 UTC+0 - measurement-conditions - DEBUG - Sun angle is above threshold.
2023-11-27 08:33:59.647783 UTC+0 - measurement-conditions - INFO - Helios as a trigger is considered.
2023-11-27 08:33:59.651756 UTC+0 - measurement-conditions - DEBUG - Helios indicates bad sun conditions.
2023-11-27 08:33:59.653742 UTC+0 - measurement-conditions - INFO - Measurements should be running is set to: False.
2023-11-27 08:33:59.681557 UTC+0 - upload - DEBUG - datalogger - 2023-08-19: found 1 files for this date
2023-11-27 08:33:59.686524 UTC+0 - enclosure-control - INFO - Running EnclosureControl
2023-11-27 08:33:59.686524 UTC+0 - upload - DEBUG - datalogger - acquiring lock on local machine at "C:\MESSUNGEN\datalogger-copy-for-upload-test\dat\.do-not-touch"
2023-11-27 08:33:59.744137 UTC+0 - upload - DEBUG - datalogger - acquiring lock on remote server at "/mnt/em27-upload/muccnet/datalogger-for-upload/ma/.do-not-touch"
2023-11-27 08:33:59.963661 UTC+0 - plc-interface - DEBUG - Connected to PLC.
2023-11-27 08:34:00.364397 UTC+0 - upload - DEBUG - datalogger - releasing lock on remote server at "/mnt/em27-upload/muccnet/datalogger-for-upload/ma/.do-not-touch"
2023-11-27 08:34:00.497233 UTC+0 - upload - DEBUG - datalogger - releasing lock on local machine at "C:\MESSUNGEN\datalogger-copy-for-upload-test\dat\.do-not-touch"
2023-11-27 08:34:00.501207 UTC+0 - upload - DEBUG - datalogger - 2023-08-19: done (successful)
2023-11-27 08:34:00.522471 UTC+0 - upload - DEBUG - datalogger - 2023-08-20: found 1 files for this date
2023-11-27 08:34:00.525325 UTC+0 - upload - DEBUG - datalogger - acquiring lock on local machine at "C:\MESSUNGEN\datalogger-copy-for-upload-test\dat\.do-not-touch"
2023-11-27 08:34:00.529193 UTC+0 - upload - DEBUG - datalogger - acquiring lock on remote server at "/mnt/em27-upload/muccnet/datalogger-for-upload/ma/.do-not-touch"
2023-11-27 08:34:01.202793 UTC+0 - upload - DEBUG - datalogger - releasing lock on remote server at "/mnt/em27-upload/muccnet/datalogger-for-upload/ma/.do-not-touch"
2023-11-27 08:34:01.320837 UTC+0 - upload - DEBUG - datalogger - releasing lock on local machine at "C:\MESSUNGEN\datalogger-copy-for-upload-test\dat\.do-not-touch"
2023-11-27 08:34:01.323798 UTC+0 - upload - DEBUG - datalogger - 2023-08-20: done (successful)
2023-11-27 08:34:01.346645 UTC+0 - upload - DEBUG - datalogger - 2023-08-21: found 1 files for this date
2023-11-27 08:34:01.349624 UTC+0 - upload - DEBUG - datalogger - acquiring lock on local machine at "C:\MESSUNGEN\datalogger-copy-for-upload-test\dat\.do-not-touch"
2023-11-27 08:34:01.352637 UTC+0 - upload - DEBUG - datalogger - acquiring lock on remote server at "/mnt/em27-upload/muccnet/datalogger-for-upload/ma/.do-not-touch"
2023-11-27 08:34:01.987209 UTC+0 - upload - DEBUG - datalogger - releasing lock on remote server at "/mnt/em27-upload/muccnet/datalogger-for-upload/ma/.do-not-touch"
2023-11-27 08:34:02.101439 UTC+0 - upload - DEBUG - datalogger - releasing lock on local machine at "C:\MESSUNGEN\datalogger-copy-for-upload-test\dat\.do-not-touch"
2023-11-27 08:34:02.104420 UTC+0 - upload - DEBUG - datalogger - 2023-08-21: done (successful)
2023-11-27 08:34:02.126276 UTC+0 - upload - DEBUG - datalogger - 2023-08-22: found 2 files for this date
2023-11-27 08:34:02.129254 UTC+0 - upload - DEBUG - datalogger - acquiring lock on local machine at "C:\MESSUNGEN\datalogger-copy-for-upload-test\dat\.do-not-touch"
2023-11-27 08:34:02.132234 UTC+0 - upload - DEBUG - datalogger - acquiring lock on remote server at "/mnt/em27-upload/muccnet/datalogger-for-upload/ma/.do-not-touch"
2023-11-27 08:34:02.685521 UTC+0 - helios - DEBUG - exposure = -12, edge_fraction = 0.007613
2023-11-27 08:34:02.688500 UTC+0 - helios - DEBUG - New Helios edge_fraction: 0.007613. Current history: [0.007382, 0.007206, 0.006854, 0.006942, 0.007371, 0.007591, 0.007701, 0.00758, 0.007899, 0.007349, 0.006964, 0.00714, 0.006975, 0.007327, 0.007613]
2023-11-27 08:34:02.691480 UTC+0 - helios - DEBUG - New state: BAD
2023-11-27 08:34:02.694462 UTC+0 - helios - DEBUG - Finished iteration, waiting 5.89 second(s).
2023-11-27 08:34:03.073914 UTC+0 - upload - DEBUG - datalogger - releasing lock on remote server at "/mnt/em27-upload/muccnet/datalogger-for-upload/ma/.do-not-touch"
2023-11-27 08:34:03.175233 UTC+0 - upload - DEBUG - datalogger - releasing lock on local machine at "C:\MESSUNGEN\datalogger-copy-for-upload-test\dat\.do-not-touch"
2023-11-27 08:34:03.181194 UTC+0 - upload - DEBUG - datalogger - 2023-08-22: done (successful)
2023-11-27 08:34:03.203048 UTC+0 - upload - DEBUG - datalogger - 2023-08-23: found 2 files for this date
2023-11-27 08:34:03.206028 UTC+0 - upload - DEBUG - datalogger - acquiring lock on local machine at "C:\MESSUNGEN\datalogger-copy-for-upload-test\dat\.do-not-touch"
2023-11-27 08:34:03.210001 UTC+0 - upload - DEBUG - datalogger - acquiring lock on remote server at "/mnt/em27-upload/muccnet/datalogger-for-upload/ma/.do-not-touch"
2023-11-27 08:34:03.960962 UTC+0 - cli - INFO - running command "plc close-cover"
2023-11-27 08:34:04.147710 UTC+0 - upload - DEBUG - datalogger - releasing lock on remote server at "/mnt/em27-upload/muccnet/datalogger-for-upload/ma/.do-not-touch"
2023-11-27 08:34:04.257969 UTC+0 - upload - DEBUG - datalogger - releasing lock on local machine at "C:\MESSUNGEN\datalogger-copy-for-upload-test\dat\.do-not-touch"
2023-11-27 08:34:04.261943 UTC+0 - upload - DEBUG - datalogger - 2023-08-23: done (successful)
2023-11-27 08:34:04.268898 UTC+0 - upload - ERROR - error in UploadThread: FileNotFoundError(2, 'No such file or directory')
2023-11-27 08:34:04.314591 UTC+0 - upload - EXCEPTION - FileNotFoundError occured: Traceback (most recent call last):

  File "C:\Users\EnclosureMb02\Documents\pyra\pyra-4.1.0\packages\core\threads\upload_thread.py", line 93, in main
    ).run()

  File "C:\Users\EnclosureMb02\AppData\Local\Programs\Python\Python310\lib\site-packages\circadian_scp_upload\client.py", line 300, in run
    if self.callbacks.should_abort_upload():

  File "C:\Users\EnclosureMb02\Documents\pyra\pyra-4.1.0\packages\core\threads\upload_thread.py", line 39, in upload_should_abort
    new_config = types.Config.load()

  File "C:\Users\EnclosureMb02\Documents\pyra\pyra-4.1.0\packages\core\types\config.py", line 319, in load
    return _read()

  File "C:\Users\EnclosureMb02\Documents\pyra\pyra-4.1.0\packages\core\types\config.py", line 309, in _read
    with open(_CONFIG_FILE_PATH) as f:

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\EnclosureMb02\\Documents\\pyra\\pyra-4.1.0\\config\\config.json'

2023-11-27 08:34:04.317569 UTC+0 - upload - INFO - sleeping 5 minutes, then restarting upload thread
2023-11-27 08:34:07.513368 UTC+0 - plc-interface - DEBUG - new plc bulk read: {3: bytearray(b'\t\x00\x05\x00 \x01'), 8: bytearray(b'\x01\x00\xc1\xeeh\x98\x00\x00=\xfb\xda\x12\x00\x00\x7f\x00\xce\x00\x00\x00\xff\xe2\x00\x00\x06\x00'), 25: bytearray(b'\x0c\x00\x04\x00\x00\x0c\x00\x00\x00\x00')}
2023-11-27 08:34:07.516329 UTC+0 - enclosure-control - INFO - New PLC readings. Writing them to the PLC logs.
2023-11-27 08:34:07.525270 UTC+0 - enclosure-control - DEBUG - Performing camera power cycle.
2023-11-27 08:34:07.528249 UTC+0 - enclosure-control - DEBUG - No camera power cycle is due.
2023-11-27 08:34:07.603743 UTC+0 - enclosure-control - DEBUG - Successful ping to PLC.
2023-11-27 08:34:07.606722 UTC+0 - plc-interface - DEBUG - Gracefully disconnected from PLC.
2023-11-27 08:34:07.609703 UTC+0 - sun-tracking - INFO - Running SunTracking
2023-11-27 08:34:08.150109 UTC+0 - sun-tracking - DEBUG - CamTracker is not running
2023-11-27 08:34:08.154052 UTC+0 - opus-measurement - INFO - Running OpusMeasurement
2023-11-27 08:34:08.700415 UTC+0 - opus-measurement - DEBUG - Successful ping to EM27.
2023-11-27 08:34:08.707337 UTC+0 - opus-measurement - DEBUG - Nothing to do for OPUSMeasurement.
2023-11-27 08:34:08.710318 UTC+0 - system-checks - INFO - Running SystemChecks
2023-11-27 08:34:09.714678 UTC+0 - system-checks - DEBUG - Current CPU usage for all cores is [29.9, 65.7, 36.9, 31.2]%.
2023-11-27 08:34:09.722626 UTC+0 - system-checks - DEBUG - Current v_memory usage for the system is 28.5.
2023-11-27 08:34:09.724611 UTC+0 - system-checks - DEBUG - The system is running since 2023-11-21 08:30:29.
2023-11-27 08:34:09.727590 UTC+0 - system-checks - DEBUG - The disk is currently filled with 9.0%.
2023-11-27 08:34:09.750441 UTC+0 - main - INFO - Ending iteration
2023-11-27 08:34:09.753419 UTC+0 - main - DEBUG - Waiting 4.8 second(s)
2023-11-27 08:34:14.558129 UTC+0 - main - INFO - Starting iteration
2023-11-27 08:34:14.958783 UTC+0 - main - ERROR - Invalid config, waiting 10 seconds: 
Error in opus.executable_path: Value error, File does not exist (value: C:\Program Files (x86)\Bruker\OPUS_7.8.44\opus.exe),
Error in opus.experiment_path: Value error, File does not exist (value: C:\Users\Public\Documents\Bruker\OPUS_7.8.44\XPM\experiment.xpm),
Error in opus.macro_path: Value error, File does not exist (value: C:\Users\Public\Documents\Bruker\OPUS_7.8.44\Macro\macro.mtx),
Error in camtracker.config_path: Value error, File does not exist (value: C:\Users\Public\Documents\Bruker\camtracker_3_9_1_0\CamTrackerConfig.txt),
Error in camtracker.executable_path: Value error, File does not exist (value: C:\Users\Public\Documents\Bruker\camtracker_3_9_1_0\CamTracker_3_9.exe),
Error in camtracker.learn_az_elev_path: Value error, File does not exist (value: C:\Users\Public\Documents\Bruker\camtracker_3_9_1_0\LEARN_Az_Elev.dat),
Error in camtracker.sun_intensity_path: Value error, File does not exist (value: C:\Users\Public\Documents\Bruker\camtracker_3_9_1_0\SunIntensity.dat)
2023-11-27 08:34:24.961787 UTC+0 - main - INFO - Starting iteration
2023-11-27 08:34:24.985636 UTC+0 - main - ERROR - Invalid config, waiting 10 seconds: 
Error in opus.executable_path: Value error, File does not exist (value: C:\Program Files (x86)\Bruker\OPUS_7.8.44\opus.exe),
... 
```

This config file deletion is caused when running "plc close-cover":

```log
01/12/2023, 12:08:22
Error while closing cover.
stdout = , stderr = Traceback (most recent call last):
  File "C:\Users\EnclosureMb02\Documents\pyra\pyra-4.1.0\packages\cli\main.py", line 53, in <module>
    cli.main(prog_name="pyra-cli")
  File "C:\Users\EnclosureMb02\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\EnclosureMb02\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\EnclosureMb02\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\EnclosureMb02\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\EnclosureMb02\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\EnclosureMb02\Documents\pyra\pyra-4.1.0\packages\cli\commands\plc.py", line 166, in _close_cover
    _enable_user_control_in_config()
  File "C:\Users\EnclosureMb02\AppData\Local\Programs\Python\Python310\lib\site-packages\tum_esm_utils\decorators.py", line 33, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\EnclosureMb02\Documents\pyra\pyra-4.1.0\packages\cli\commands\plc.py", line 153, in _enable_user_control_in_config
    config = types.Config.load(with_filelock=False)
  File "C:\Users\EnclosureMb02\Documents\pyra\pyra-4.1.0\packages\core\types\config.py", line 321, in load
    return _read()
  File "C:\Users\EnclosureMb02\Documents\pyra\pyra-4.1.0\packages\core\types\config.py", line 311, in _read
    f.read(),
PermissionError: [Errno 13] Permission denied
```

**Comment by dostuffthatmatters** [comment]
The line (https://github.com/tum-esm/pyra/blob/f52f09df549716f043b9a0cfb7d1d2c2872ec394/packages/cli/commands/plc.py#L122) was pointing to the config file, not the config lock file (that prevents multiple processes from accessing the file). This means, every time it tried to lock it, it empties the whole file.
